CREATE DATABASE BDSISTEMADEVENTA
GO
USE BDSISTEMADEVENTA
GO
CREATE TABLE CLIENTE
(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO_PATERNO VARCHAR (50) NOT NULL,
APELLIDO_MATERNO VARCHAR (50) NOT NULL,

)
GO